CREATE DATABASE DATA_AND_TIME;

USE DATA_AND_TIME;

CREATE TABLE EMPLOYEE
(
	PID INTEGER AUTO_INCREMENT,
    P_BIRTHDATE DATE,
    P_JOINING_DATE DATETIME,
    P_RETIREMENT_DATE DATE,
    P_EXPIRE_DATE DATETIME,
    CONSTRAINT PK_KEY PRIMARY KEY(PID)
);

INSERT INTO EMPLOYEE (P_BIRTHDATE, P_JOINING_DATE, P_RETIREMENT_DATE, P_EXPIRE_DATE) VALUES
('1995-12-09', CURRENT_DATE(), '1995-12-10', CURRENT_TIMESTAMP());

SELECT * FROM EMPLOYEE;

SELECT DATE_FORMAT(P_BIRTHDATE, '%D-%M-%Y') FROM EMPLOYEE;
/*
9th-December-1995
*/

SELECT DATE_FORMAT(P_BIRTHDATE, '%d-%m-%y') FROM EMPLOYEE;
/*
09-12-95
*/

SELECT DATE_FORMAT(P_BIRTHDATE, '%W-%D-%M-%Y') FROM EMPLOYEE;
/*
Saturday-9th-December-1995
*/

SELECT DATE_FORMAT(P_BIRTHDATE, '%W-%d-%m-%y') FROM EMPLOYEE;
/*
Saturday-09-12-95
*/

SELECT DATE_FORMAT(P_BIRTHDATE, '%w-%d-%m-%y') FROM EMPLOYEE;
/*
6-09-12-95
*/

SELECT DATE_FORMAT(P_BIRTHDATE, '%W-%d-%b-%y') FROM EMPLOYEE;
/*
Saturday-09-Dec-95
*/

SELECT DATE_FORMAT(P_BIRTHDATE, '%W-%d-%B-%y') FROM EMPLOYEE;
/*
Saturday-09-B-95		//NI DAALNA '%B'
*/

SELECT DATE_FORMAT(P_BIRTHDATE, '%W-%d-%m-%y') FROM EMPLOYEE;

SELECT CURRENT_TIMESTAMP();
/*
2020-12-15 14:12:25
*/
SELECT current_date();
/*
2020-12-16
*/

SELECT SYSDATE();
/*
2020-12-16 12:15:47
*/

SELECT CURRENT_TIMESTAMP();
/*
2020-12-16 12:16:51
*/


SELECT DATE_FORMAT(P_BIRTHDATE, '%W-%d-%m-%y') FROM EMPLOYEE;

DROP TABLE EMPLOYEE;