CREATE DATABASE MINI_OLX;

USE MINI_OLX;

CREATE TABLE MOBILES
(
	PRO_ID INTEGER,
	MOB_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	MOB_TYPE VARCHAR(30),
    MOB_RAM VARCHAR(30),
    MOB_CAMERA VARCHAR(30),
    MOB_STORAGE VARCHAR(30),
    MOB_MODEL VARCHAR(30),
    MOB_COMPANY VARCHAR(30),
    MOB_PRICE INTEGER(6) NOT NULL,
    CONSTRAINT FOREIGN KEY(PRO_ID) REFERENCES PRODUCT(PRO_ID)
);

INSERT INTO MOBILES (PRO_ID, MOB_TYPE, MOB_RAM, MOB_CAMERA, MOB_STORAGE, MOB_MODEL, MOB_COMPANY, MOB_PRICE) VALUES
(10001, 'NEW', '4GB', '16MP', '32GB', 'LG50S', 'LG', 10000);
INSERT INTO MOBILES (PRO_ID, MOB_TYPE, MOB_RAM, MOB_CAMERA, MOB_STORAGE, MOB_MODEL, MOB_COMPANY, MOB_PRICE) VALUES
(10001, 'OLD', '4GB', '48MP', '32GB', 'OP2015', 'ONEPLUS', 22000);
INSERT INTO MOBILES (PRO_ID, MOB_TYPE, MOB_RAM, MOB_CAMERA, MOB_STORAGE, MOB_MODEL, MOB_COMPANY, MOB_PRICE) VALUES
(10001, 'NEW', '6GB', '48MP', '32GB', 'OP2017', 'ONEPLUS', 30000);
INSERT INTO MOBILES (PRO_ID, MOB_TYPE, MOB_RAM, MOB_CAMERA, MOB_STORAGE, MOB_MODEL, MOB_COMPANY, MOB_PRICE) VALUES
(10001, 'OLD', '4GB', '8MP', '16GB', 'SS300S', 'SAMSUNG', 14000);
INSERT INTO MOBILES (PRO_ID, MOB_TYPE, MOB_RAM, MOB_CAMERA, MOB_STORAGE, MOB_MODEL, MOB_COMPANY, MOB_PRICE) VALUES
(10001, 'NEW', '4GB', '16MP', '32GB', 'PP50S', 'OPPO', 17000);




CREATE TABLE LAPTOP
(
	PRO_ID INTEGER,
	LAP_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    LAP_TYPE VARCHAR(30),
    LAP_COMPANY VARCHAR(30),
    LAP_PROCESSOR VARCHAR(30),
    LAP_RAM VARCHAR(30),
    LAP_HARDDISK VARCHAR(30),
    LAP_MODEL VARCHAR(30),
    LAP_PRICE INTEGER(6) NOT NULL,
    CONSTRAINT FOREIGN KEY(PRO_ID) REFERENCES PRODUCT(PRO_ID)
);

INSERT INTO LAPTOP (PRO_ID, LAP_TYPE, LAP_COMPANY, LAP_PROCESSOR, LAP_RAM, LAP_HARDDISK, LAP_MODEL, LAP_PRICE) VALUES
(10002, 'NEW', 'HP', 'I5', '8GB', '2TB', 'HP180TX', 46000);
INSERT INTO LAPTOP (PRO_ID, LAP_TYPE, LAP_COMPANY, LAP_PROCESSOR, LAP_RAM, LAP_HARDDISK, LAP_MODEL, LAP_PRICE) VALUES
(10002, 'OLD', 'HP', 'I5', '6GB', '1TB', 'HP2007', 33000);
INSERT INTO LAPTOP (PRO_ID, LAP_TYPE, LAP_COMPANY, LAP_PROCESSOR, LAP_RAM, LAP_HARDDISK, LAP_MODEL, LAP_PRICE) VALUES
(10002, 'OLD', 'DELL', 'I3', '4GB', '500GB', 'DL120', 20000);
INSERT INTO LAPTOP (PRO_ID, LAP_TYPE, LAP_COMPANY, LAP_PROCESSOR, LAP_RAM, LAP_HARDDISK, LAP_MODEL, LAP_PRICE) VALUES
(10002, 'OLD', 'DELL', 'I3', '4GB', '1TB', 'DL210', 46000);
INSERT INTO LAPTOP (PRO_ID, LAP_TYPE, LAP_COMPANY, LAP_PROCESSOR, LAP_RAM, LAP_HARDDISK, LAP_MODEL, LAP_PRICE) VALUES
(10002, 'OLD', 'ASUS', 'I5', '8GB', '1TB', 'AU101', 35000);






CREATE TABLE BIKES
(
	PRO_ID INTEGER,
	BIK_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    BIK_TYPE VARCHAR(30),
    BIK_COMPANY VARCHAR(30),
    BIK_MILAGE INTEGER(5),
    BIK_MODEL VARCHAR(30),
    BIK_PRICE INTEGER(6) NOT NULL,
    CONSTRAINT FOREIGN KEY(PRO_ID) REFERENCES PRODUCT(PRO_ID)
);

INSERT INTO BIKES (PRO_ID, BIK_TYPE, BIK_COMPANY, BIK_MILAGE, BIK_MODEL, BIK_PRICE) VALUES
(10003, 'NEW', 'HONDA', 50, 'H500Z', 70000);
INSERT INTO BIKES (PRO_ID, BIK_TYPE, BIK_COMPANY, BIK_MILAGE, BIK_MODEL, BIK_PRICE) VALUES
(10003, 'OLD', 'BAJAJ TVS', 40, 'BJ2007', 20000);
INSERT INTO BIKES (PRO_ID, BIK_TYPE, BIK_COMPANY, BIK_MILAGE, BIK_MODEL, BIK_PRICE) VALUES
(10003, 'OLD', 'SUZUKI REVOLT', 42, 'SZ00Z', 22000);
INSERT INTO BIKES (PRO_ID, BIK_TYPE, BIK_COMPANY, BIK_MILAGE, BIK_MODEL, BIK_PRICE) VALUES
(10003, 'NEW', 'VESPA', 47, 'VP009', 65000);
INSERT INTO BIKES (PRO_ID, BIK_TYPE, BIK_COMPANY, BIK_MILAGE, BIK_MODEL, BIK_PRICE) VALUES
(10003, 'OLD', 'ROYAL ENFIELD', 55, 'RE01', 100000);





CREATE TABLE WASHING_MACHINE
(
	PRO_ID INTEGER,
	WM_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    WM_TYPE VARCHAR(30),
    WM_COMPANY VARCHAR(30),
    WM_CAPACITY INTEGER(5),
    WM_MODEL VARCHAR(30),
    WM_PRICE INTEGER(6),
    CONSTRAINT FOREIGN KEY(PRO_ID) REFERENCES PRODUCT(PRO_ID)
);
INSERT INTO WASHING_MACHINE (PRO_ID, WM_TYPE, WM_COMPANY, WM_CAPACITY, WM_MODEL, WM_PRICE) VALUES
(10004, 'NEW', 'LG', 5, 'LG402', 20000);
INSERT INTO WASHING_MACHINE (PRO_ID, WM_TYPE, WM_COMPANY, WM_CAPACITY, WM_MODEL, WM_PRICE) VALUES
(10004, 'OLD', 'LG', 5, 'LG406', 12000);
INSERT INTO WASHING_MACHINE (PRO_ID, WM_TYPE, WM_COMPANY, WM_CAPACITY, WM_MODEL, WM_PRICE) VALUES
(10004, 'OLD', 'SAMSUNG', 4, 'SS300', 13500);
INSERT INTO WASHING_MACHINE (PRO_ID, WM_TYPE, WM_COMPANY, WM_CAPACITY, WM_MODEL, WM_PRICE) VALUES
(10004, 'OLD', 'LG', 7, 'LG426', 12000);
INSERT INTO WASHING_MACHINE (PRO_ID, WM_TYPE, WM_COMPANY, WM_CAPACITY, WM_MODEL, WM_PRICE) VALUES
(10004, 'NEW', 'WHIRLPOOL', 5, 'WP700', 12000);





CREATE TABLE PRODUCT
(
	PRO_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    PRO_CODE VARCHAR(10),
    PRO_NAME VARCHAR(20)
);
INSERT INTO PRODUCT VALUES
(10001, 'MB10001', 'MOBILE');
INSERT INTO PRODUCT VALUES
(10002, 'LP10002', 'LAPTOP');
INSERT INTO PRODUCT VALUES
(10003, 'LP10003', 'BIKES');
INSERT INTO PRODUCT VALUES
(10004, 'WM10004', 'WASHING_MACHINE');

SELECT * FROM PRODUCT;

CREATE TABLE USERS
(
	USER_ID INTEGER NOT NULL,
    USER_NAME VARCHAR(20) NOT NULL,
    USER_PASSWORD VARCHAR(20) NOT NULL,
    USER_EMAIL VARCHAR(20) NOT NULL,
    USER_MOB_NO INTEGER(10)
);


CREATE TABLE CART
(
	CART_NO INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
	PRO_ID INTEGER PRIMARY KEY,
    ID INTEGER,
    PRO_PRICE INTEGER
);



SHOW TABLES;

SELECT * FROM PRODUCT;
SELECT * FROM LAPTOP;
SELECT * FROM BIKES;
SELECT * FROM MOBILES;
SELECT * FROM WASHING_MACHINE;






CREATE PROCEDURE 










DROP TABLE LAPTOP;
DROP TABLE BIKES;
DROP TABLE MOBILES;
DROP TABLE WASHING_MACHINE;